version: "3.9"
services:   
  analyzer_tests:
    build:
     context: analyzer_manager/.
     dockerfile: DockerfileAutomation
    command: python3 -m pytest ./tests/analytics/test_basic -m "not extended"
    runtime: nvidia
    depends_on:
      - inference_server

  inference_server:
    build: analyzer_manager/inference/.
    runtime: nvidia
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - "${HOME}/assets/:/assets/"